[package]
name = "event"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
features = "0.10.0"
mongodb = "3.2.0"
serde = "1.0.217"
tokio = "1.43.0"
shared = { path = "../shared" }
serde_json = "1.0.137"
